### PR TITLE
Formatting tweaks.

### PR DESCRIPTION
**Pull request by himedlooff**

### CODE REVIEW

**Comment by himedlooff** [comment]
@Scotchester, I'm not exactly sure where we land with the topdoc comment formatting, 4 spaces or 2? For example:

https://github.com/cfpb/cf-buttons/blob/gh-pages/src/cf-buttons.less#L6-L46
VS
https://github.com/himedlooff/cf-core/blob/gh-pages/src/cf-base.less#L10-L44

Do you have a preference? We seem to be all over the place.

**Comment by Scotchester** [comment]
It looks like the only difference between those two is that in the first one, the first indention of each line was 4 spaces, and the rest were all 2s.

YAML recommends 2 space-indents, so I think we should standardize on that everywhere.

**Comment by himedlooff** [comment]
Ok thanks

**Comment by himedlooff** [comment]
This is ready for merging!

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
