### PR TITLE
Restrict transition to background-color

### LINKED ISSUE #31: Remove transition on everything
It makes EVERYTHING animated including absolutely positioning things.

### PR DESCRIPTION
**Pull request by Scotchester**
(fixes #31)

### CODE REVIEW

**Comment by Scotchester** [comment]
:warning: **NOT READY FOR MERGING** :warning: 

Something's not right with the doc builds.

**Comment by Scotchester** [comment]
Nevermind, all is good. I was thrown off by the massive horizontal scroll in the split diff view.

All good, pending a review.

**Comment by jimmynotjim** [comment]
:+1: LGTM

**Comment by Scotchester** [comment]
Thanks!

**Pull request merged**
