### PR TITLE
You can now use the disabled attribute in place of .btn__disabled if you want to.

### LINKED ISSUE #4: Update disabled selector to use the disabled attribute
Like this:

``` CSS
.btn:disabled,
.btn-disabled,
... {
  ...
}
```

### PR DESCRIPTION
**Pull request by himedlooff**
Closes #4.

### CODE REVIEW

**Comment by Scotchester** [comment]
Nice! Thanks :+1:

**Comment by anselmbradford** [comment]
So cool!

**Comment by jimmynotjim** [comment]
Still contributing, that @himedlooff is more awesome than I think I'll ever be

**Comment by himedlooff** [comment]
ABC, always be contributing :boom:

**Pull request merged**
