### PR TITLE
Fixes #38 - btn__link color

### LINKED ISSUE #38: btn__link border color is Pacific 80%, design manual links are Pacific 50%
cf-buttons contains a `btn__link` style that is a link that has button associated classes. The underline on the link is set to the background color for a button [here](https://github.com/cfpb/cf-buttons/blob/gh-pages/src/cf-buttons.less#L866).

The design manual shows buttons as having a [Pacific 80% background](http://cfpb.github.io/design-manual/ui-toolkit/buttons.html) on hover, however it also shows links have a [Pacific 50% underline](http://cfpb.github.io/design-manual/ui-toolkit/links.html) on hover. By using the button background as the underline color, the hover state for `btn__link` diverges from that set in the design manual.

Do links have a place in cf-buttons at all? Should they be migrated to cf-typography?

### PR DESCRIPTION
**Pull request by anselmbradford**
`btn__link` used the button background color, which makes it not aligned with the CFPB style guide where button and link colors differ.
## Changes
- Fixes #38 - btn__link color
- Updates changelog with unreleased changes.
- regenerates assets.
## Review
- @Scotchester 
- @jimmynotjim 
- @sebworks 
- @virginiacc 
## Notes
- I added the changes to an `Unreleased` section in `CHANGELOG.md`, it appears the repo uses a [distinct bump commit](https://github.com/cfpb/cf-buttons/commit/e8cf8f27e185fab99e0334a88a05331fb102e1c6) to make a release and do the tagging, but more guidance is recommended in https://github.com/cfpb/cf-buttons/issues/39

### CODE REVIEW

**Comment by jimmynotjim** [comment]
This looks good from me, but I don't know this component as well as some others do.

**Comment by Scotchester** [comment]
Code change looks good.

Re: bump commits. That's not a pattern we intentionally followed. It usually happened due to forgetting to bump the first time around. That said, I have recently been intentionally doing them, because I think it's not a bad idea to have the version bump and CHANGELOG updates in their own commit. Not sure how others feel about this. In any case, I would include the version bump in the PR, regardless. Creating separate PRs for version bumping seems like overkill.

**Comment by anselmbradford** [comment]
Bumped in https://github.com/anselmbradford/cf-buttons/commit/a6b201a60a416f0c464336e3e852283ace19d1ba GTG?

**Comment by Scotchester** [comment]
:+1:

**Comment by anselmbradford** [comment]
https://github.com/cfpb/cf-buttons/tree/1.4.2

**Pull request merged**
