### PR TITLE
Rebuild docs and demos with new version of cf-component-demo.

### PR DESCRIPTION
**Pull request by himedlooff**
Looks like it also updates the banner in the CSS file.

Not sure what's up with the font awesome line endings though.

### CODE REVIEW

**Comment by himedlooff** [comment]
My `Rebuilds docs and demos with updated cf-component-demo and font awesome.` commit is misleading now that I look into it. It seems that the line endings have changed somehow. There was no update to cf-component-demo making this change. Looking into it.

**Comment by himedlooff** [comment]
Can't figure it out but @Scotchester is getting the same line-ending changes when rebuilding so I think we should just roll with it. Any objections?

This also means rebuilding the other components as well.

**Comment by Scotchester** [comment]
Well, this isn't providing any urgently-needed updates. I think we can wait until we naturally need to update the demo/docs.

**Comment by himedlooff** [comment]
My concern is that anyone forking this and simply running grunt will have modified files for no reason. I think we should remove this confusion.

**Comment by Scotchester** [comment]
Ah yes, that is a good point.

**Comment by himedlooff** [comment]
I think we should update all repos then.

**Comment by Scotchester** [comment]
Yeah, probably should.

**Comment by Scotchester** [comment]
Just to be clear, this is ready to merge then, right?

**Comment by himedlooff** [comment]
Yes, ready to merge.

**Pull request merged**
